// <auto-generated />
using System;
using AumoFinance.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AumoFinance.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            BuildDomainEntities(modelBuilder);
            BuildSecurityEntities(modelBuilder);
            BuildIdentityEntities(modelBuilder);
            BuildRelationships(modelBuilder);
#pragma warning restore 612, 618
        }

        static partial void BuildDomainEntities(ModelBuilder modelBuilder);
        static partial void BuildSecurityEntities(ModelBuilder modelBuilder);
        static partial void BuildIdentityEntities(ModelBuilder modelBuilder);
        static partial void BuildRelationships(ModelBuilder modelBuilder);
    }
}
