-- Jalankan di Neon SQL Editor.
-- Perbaikan: tabel TransactionCounters sudah ada, tapi kemungkinan unique
-- index-nya BELUM terbentuk. Ini terjadi kalau script sebelumnya
-- (manual-neon-run-transaction-counters.sql) dijalankan sebagai satu batch
-- dan baris CREATE TABLE gagal (mis. karena tabel sudah dibuat lebih dulu
-- di percobaan sebelumnya) — beberapa SQL editor langsung berhenti di baris
-- pertama yang error, jadi baris CREATE UNIQUE INDEX setelahnya tidak
-- pernah sempat dijalankan.
--
-- Tanpa index unik pada (UserId, CounterKey), UPSERT atomik di
-- TransactionNumberService (ON CONFLICT ("UserId", "CounterKey")) akan
-- gagal dengan error Postgres "no unique or exclusion constraint matching
-- the ON CONFLICT specification" — inilah penyebab "server error" saat
-- menyimpan jurnal.
--
-- Script ini aman dijalankan berapa kali pun (IF NOT EXISTS di kedua
-- baris), jadi tidak masalah kalau tabelnya sudah ada atau belum.

CREATE TABLE IF NOT EXISTS "TransactionCounters" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" uuid NOT NULL,
    "CounterKey" character varying(10) NOT NULL,
    "LastSequence" integer NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_TransactionCounters_UserId_CounterKey"
    ON "TransactionCounters" ("UserId", "CounterKey");
