-- Jalankan di Neon SQL Editor.
-- Tabel baru: TransactionCounters — counter atomik untuk penomoran
-- transaksi jurnal (GJ26080001 / AJ26080001, format PREFIX+YYMM+SEQUENCE
-- 4 digit). Satu baris per kombinasi user + prefix + periode (CounterKey,
-- contoh "GJ2608"). LastSequence dinaikkan lewat UPSERT atomik
-- (INSERT ... ON CONFLICT DO UPDATE ... RETURNING) di
-- TransactionNumberService — bukan MAX(TransactionNumber)+1 — supaya aman
-- terhadap dua user/request yang membuat jurnal secara bersamaan.

CREATE TABLE "TransactionCounters" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" uuid NOT NULL,
    "CounterKey" character varying(10) NOT NULL,
    "LastSequence" integer NOT NULL
);

CREATE UNIQUE INDEX "IX_TransactionCounters_UserId_CounterKey"
    ON "TransactionCounters" ("UserId", "CounterKey");
