-- 1. Tabel MobileJournalEntries (header input dari Android, terpisah dari JournalEntries)
CREATE TABLE IF NOT EXISTS "MobileJournalEntries" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "EntryDate" timestamp with time zone NOT NULL,
    "Mode" character varying(20) NOT NULL,
    "Type" character varying(20) NULL,
    "Amount" decimal(18,2) NULL,
    "Note" text NULL,
    "Status" character varying(20) NOT NULL DEFAULT 'Pending',
    "SubmittedAt" timestamp with time zone NOT NULL,
    "VerifiedAt" timestamp with time zone NULL,
    "RejectedAt" timestamp with time zone NULL,
    "VerifiedJournalEntryId" integer NULL,
    CONSTRAINT "FK_MobileJournalEntries_JournalEntries_VerifiedJournalEntryId"
        FOREIGN KEY ("VerifiedJournalEntryId") REFERENCES "JournalEntries" ("Id") ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS "IX_MobileJournalEntries_Status" ON "MobileJournalEntries" ("Status");
CREATE INDEX IF NOT EXISTS "IX_MobileJournalEntries_VerifiedJournalEntryId" ON "MobileJournalEntries" ("VerifiedJournalEntryId");

-- 2. Tabel MobileJournalEntryLines (baris untuk Mode = 'Manual', akun sudah dipilih dari app)
CREATE TABLE IF NOT EXISTS "MobileJournalEntryLines" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "MobileJournalEntryId" integer NOT NULL,
    "AccountId" integer NOT NULL,
    "LineDescription" character varying(250) NULL,
    "Debit" decimal(18,2) NOT NULL,
    "Credit" decimal(18,2) NOT NULL,
    "LineOrder" integer NOT NULL,
    CONSTRAINT "FK_MobileJournalEntryLines_MobileJournalEntries_MobileJournalEntryId"
        FOREIGN KEY ("MobileJournalEntryId") REFERENCES "MobileJournalEntries" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_MobileJournalEntryLines_ChartOfAccounts_AccountId"
        FOREIGN KEY ("AccountId") REFERENCES "ChartOfAccounts" ("Id") ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS "IX_MobileJournalEntryLines_AccountId" ON "MobileJournalEntryLines" ("AccountId");
CREATE INDEX IF NOT EXISTS "IX_MobileJournalEntryLines_MobileJournalEntryId" ON "MobileJournalEntryLines" ("MobileJournalEntryId");

-- 3. Catat migrasi di riwayat EF Core supaya "dotnet ef database update"
--    berikutnya tidak mencoba menjalankan ulang perubahan yang sama.
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
SELECT '20260731050000_AddMobileTables', '8.0.10'
WHERE NOT EXISTS (SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731050000_AddMobileTables');
