/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root.tsx'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiassistantRouteImport } from './routes/aiassistant.tsx'
import { Route as AuthRouteImport } from './routes/auth.tsx'
import { Route as ChartOfAccountsRouteImport } from './routes/chart-of-accounts.tsx'
import { Route as DashboardRouteImport } from './routes/dashboard.tsx'
import { Route as GuardianRouteImport } from './routes/guardian.tsx'
import { Route as JournalEntryRouteImport } from './routes/journal-entry.tsx'
import { Route as PeriodsRouteImport } from './routes/periods.tsx'
import { Route as SettingsRouteImport } from './routes/settings.tsx'
import { Route as ToolsRouteImport } from './routes/tools.tsx'
import { Route as ReportsAdjustedTrialBalanceRouteImport } from './routes/reports/adjusted-trial-balance.tsx'
import { Route as ReportsAdjustingJournalRouteImport } from './routes/reports/adjusting-journal.tsx'
import { Route as ReportsClosingJournalRouteImport } from './routes/reports/closing-journal.tsx'
import { Route as ReportsGeneralJournalRouteImport } from './routes/reports/general-journal.tsx'
import { Route as ReportsGeneralLedgerPermanentRouteImport } from './routes/reports/general-ledger-permanent.tsx'
import { Route as ReportsGeneralLedgerTemporaryRouteImport } from './routes/reports/general-ledger-temporary.tsx'
import { Route as ReportsIncomeStatementRouteImport } from './routes/reports/income-statement.tsx'
import { Route as ReportsPostClosingTrialBalanceRouteImport } from './routes/reports/post-closing-trial-balance.tsx'
import { Route as ReportsRetainedEarningsRouteImport } from './routes/reports/retained-earnings.tsx'
import { Route as ReportsStatementOfCashFlowRouteImport } from './routes/reports/statement-of-cash-flow.tsx'
import { Route as ReportsStatementOfFinancialPositionRouteImport } from './routes/reports/statement-of-financial-position.tsx'
import { Route as ReportsTrialBalanceRouteImport } from './routes/reports/trial-balance.tsx'
import { Route as ReportsUnadjustedTrialBalanceRouteImport } from './routes/reports/unadjusted-trial-balance.tsx'
import { Route as ReportsWorksheetRouteImport } from './routes/reports/worksheet.tsx'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiassistantRoute = AiassistantRouteImport.update({
  id: '/aiassistant',
  path: '/aiassistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartOfAccountsRoute = ChartOfAccountsRouteImport.update({
  id: '/chart-of-accounts',
  path: '/chart-of-accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardianRoute = GuardianRouteImport.update({
  id: '/guardian',
  path: '/guardian',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalEntryRoute = JournalEntryRouteImport.update({
  id: '/journal-entry',
  path: '/journal-entry',
  getParentRoute: () => rootRouteImport,
} as any)
const PeriodsRoute = PeriodsRouteImport.update({
  id: '/periods',
  path: '/periods',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsAdjustedTrialBalanceRoute =
  ReportsAdjustedTrialBalanceRouteImport.update({
    id: '/reports/adjusted-trial-balance',
    path: '/reports/adjusted-trial-balance',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReportsAdjustingJournalRoute = ReportsAdjustingJournalRouteImport.update({
  id: '/reports/adjusting-journal',
  path: '/reports/adjusting-journal',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsClosingJournalRoute = ReportsClosingJournalRouteImport.update({
  id: '/reports/closing-journal',
  path: '/reports/closing-journal',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsGeneralJournalRoute = ReportsGeneralJournalRouteImport.update({
  id: '/reports/general-journal',
  path: '/reports/general-journal',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsGeneralLedgerPermanentRoute =
  ReportsGeneralLedgerPermanentRouteImport.update({
    id: '/reports/general-ledger-permanent',
    path: '/reports/general-ledger-permanent',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReportsGeneralLedgerTemporaryRoute =
  ReportsGeneralLedgerTemporaryRouteImport.update({
    id: '/reports/general-ledger-temporary',
    path: '/reports/general-ledger-temporary',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReportsIncomeStatementRoute = ReportsIncomeStatementRouteImport.update({
  id: '/reports/income-statement',
  path: '/reports/income-statement',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsPostClosingTrialBalanceRoute =
  ReportsPostClosingTrialBalanceRouteImport.update({
    id: '/reports/post-closing-trial-balance',
    path: '/reports/post-closing-trial-balance',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReportsRetainedEarningsRoute = ReportsRetainedEarningsRouteImport.update({
  id: '/reports/retained-earnings',
  path: '/reports/retained-earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsStatementOfCashFlowRoute =
  ReportsStatementOfCashFlowRouteImport.update({
    id: '/reports/statement-of-cash-flow',
    path: '/reports/statement-of-cash-flow',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReportsStatementOfFinancialPositionRoute =
  ReportsStatementOfFinancialPositionRouteImport.update({
    id: '/reports/statement-of-financial-position',
    path: '/reports/statement-of-financial-position',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReportsTrialBalanceRoute = ReportsTrialBalanceRouteImport.update({
  id: '/reports/trial-balance',
  path: '/reports/trial-balance',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsUnadjustedTrialBalanceRoute =
  ReportsUnadjustedTrialBalanceRouteImport.update({
    id: '/reports/unadjusted-trial-balance',
    path: '/reports/unadjusted-trial-balance',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReportsWorksheetRoute = ReportsWorksheetRouteImport.update({
  id: '/reports/worksheet',
  path: '/reports/worksheet',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aiassistant': typeof AiassistantRoute
  '/auth': typeof AuthRoute
  '/chart-of-accounts': typeof ChartOfAccountsRoute
  '/dashboard': typeof DashboardRoute
  '/guardian': typeof GuardianRoute
  '/journal-entry': typeof JournalEntryRoute
  '/periods': typeof PeriodsRoute
  '/settings': typeof SettingsRoute
  '/tools': typeof ToolsRoute
  '/reports/adjusted-trial-balance': typeof ReportsAdjustedTrialBalanceRoute
  '/reports/adjusting-journal': typeof ReportsAdjustingJournalRoute
  '/reports/closing-journal': typeof ReportsClosingJournalRoute
  '/reports/general-journal': typeof ReportsGeneralJournalRoute
  '/reports/general-ledger-permanent': typeof ReportsGeneralLedgerPermanentRoute
  '/reports/general-ledger-temporary': typeof ReportsGeneralLedgerTemporaryRoute
  '/reports/income-statement': typeof ReportsIncomeStatementRoute
  '/reports/post-closing-trial-balance': typeof ReportsPostClosingTrialBalanceRoute
  '/reports/retained-earnings': typeof ReportsRetainedEarningsRoute
  '/reports/statement-of-cash-flow': typeof ReportsStatementOfCashFlowRoute
  '/reports/statement-of-financial-position': typeof ReportsStatementOfFinancialPositionRoute
  '/reports/trial-balance': typeof ReportsTrialBalanceRoute
  '/reports/unadjusted-trial-balance': typeof ReportsUnadjustedTrialBalanceRoute
  '/reports/worksheet': typeof ReportsWorksheetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aiassistant': typeof AiassistantRoute
  '/auth': typeof AuthRoute
  '/chart-of-accounts': typeof ChartOfAccountsRoute
  '/dashboard': typeof DashboardRoute
  '/guardian': typeof GuardianRoute
  '/journal-entry': typeof JournalEntryRoute
  '/periods': typeof PeriodsRoute
  '/settings': typeof SettingsRoute
  '/tools': typeof ToolsRoute
  '/reports/adjusted-trial-balance': typeof ReportsAdjustedTrialBalanceRoute
  '/reports/adjusting-journal': typeof ReportsAdjustingJournalRoute
  '/reports/closing-journal': typeof ReportsClosingJournalRoute
  '/reports/general-journal': typeof ReportsGeneralJournalRoute
  '/reports/general-ledger-permanent': typeof ReportsGeneralLedgerPermanentRoute
  '/reports/general-ledger-temporary': typeof ReportsGeneralLedgerTemporaryRoute
  '/reports/income-statement': typeof ReportsIncomeStatementRoute
  '/reports/post-closing-trial-balance': typeof ReportsPostClosingTrialBalanceRoute
  '/reports/retained-earnings': typeof ReportsRetainedEarningsRoute
  '/reports/statement-of-cash-flow': typeof ReportsStatementOfCashFlowRoute
  '/reports/statement-of-financial-position': typeof ReportsStatementOfFinancialPositionRoute
  '/reports/trial-balance': typeof ReportsTrialBalanceRoute
  '/reports/unadjusted-trial-balance': typeof ReportsUnadjustedTrialBalanceRoute
  '/reports/worksheet': typeof ReportsWorksheetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aiassistant': typeof AiassistantRoute
  '/auth': typeof AuthRoute
  '/chart-of-accounts': typeof ChartOfAccountsRoute
  '/dashboard': typeof DashboardRoute
  '/guardian': typeof GuardianRoute
  '/journal-entry': typeof JournalEntryRoute
  '/periods': typeof PeriodsRoute
  '/settings': typeof SettingsRoute
  '/tools': typeof ToolsRoute
  '/reports/adjusted-trial-balance': typeof ReportsAdjustedTrialBalanceRoute
  '/reports/adjusting-journal': typeof ReportsAdjustingJournalRoute
  '/reports/closing-journal': typeof ReportsClosingJournalRoute
  '/reports/general-journal': typeof ReportsGeneralJournalRoute
  '/reports/general-ledger-permanent': typeof ReportsGeneralLedgerPermanentRoute
  '/reports/general-ledger-temporary': typeof ReportsGeneralLedgerTemporaryRoute
  '/reports/income-statement': typeof ReportsIncomeStatementRoute
  '/reports/post-closing-trial-balance': typeof ReportsPostClosingTrialBalanceRoute
  '/reports/retained-earnings': typeof ReportsRetainedEarningsRoute
  '/reports/statement-of-cash-flow': typeof ReportsStatementOfCashFlowRoute
  '/reports/statement-of-financial-position': typeof ReportsStatementOfFinancialPositionRoute
  '/reports/trial-balance': typeof ReportsTrialBalanceRoute
  '/reports/unadjusted-trial-balance': typeof ReportsUnadjustedTrialBalanceRoute
  '/reports/worksheet': typeof ReportsWorksheetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aiassistant'
    | '/auth'
    | '/chart-of-accounts'
    | '/dashboard'
    | '/guardian'
    | '/journal-entry'
    | '/periods'
    | '/settings'
    | '/tools'
    | '/reports/adjusted-trial-balance'
    | '/reports/adjusting-journal'
    | '/reports/closing-journal'
    | '/reports/general-journal'
    | '/reports/general-ledger-permanent'
    | '/reports/general-ledger-temporary'
    | '/reports/income-statement'
    | '/reports/post-closing-trial-balance'
    | '/reports/retained-earnings'
    | '/reports/statement-of-cash-flow'
    | '/reports/statement-of-financial-position'
    | '/reports/trial-balance'
    | '/reports/unadjusted-trial-balance'
    | '/reports/worksheet'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aiassistant'
    | '/auth'
    | '/chart-of-accounts'
    | '/dashboard'
    | '/guardian'
    | '/journal-entry'
    | '/periods'
    | '/settings'
    | '/tools'
    | '/reports/adjusted-trial-balance'
    | '/reports/adjusting-journal'
    | '/reports/closing-journal'
    | '/reports/general-journal'
    | '/reports/general-ledger-permanent'
    | '/reports/general-ledger-temporary'
    | '/reports/income-statement'
    | '/reports/post-closing-trial-balance'
    | '/reports/retained-earnings'
    | '/reports/statement-of-cash-flow'
    | '/reports/statement-of-financial-position'
    | '/reports/trial-balance'
    | '/reports/unadjusted-trial-balance'
    | '/reports/worksheet'
  id:
    | '__root__'
    | '/'
    | '/aiassistant'
    | '/auth'
    | '/chart-of-accounts'
    | '/dashboard'
    | '/guardian'
    | '/journal-entry'
    | '/periods'
    | '/settings'
    | '/tools'
    | '/reports/adjusted-trial-balance'
    | '/reports/adjusting-journal'
    | '/reports/closing-journal'
    | '/reports/general-journal'
    | '/reports/general-ledger-permanent'
    | '/reports/general-ledger-temporary'
    | '/reports/income-statement'
    | '/reports/post-closing-trial-balance'
    | '/reports/retained-earnings'
    | '/reports/statement-of-cash-flow'
    | '/reports/statement-of-financial-position'
    | '/reports/trial-balance'
    | '/reports/unadjusted-trial-balance'
    | '/reports/worksheet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiassistantRoute: typeof AiassistantRoute
  AuthRoute: typeof AuthRoute
  ChartOfAccountsRoute: typeof ChartOfAccountsRoute
  DashboardRoute: typeof DashboardRoute
  GuardianRoute: typeof GuardianRoute
  JournalEntryRoute: typeof JournalEntryRoute
  PeriodsRoute: typeof PeriodsRoute
  SettingsRoute: typeof SettingsRoute
  ToolsRoute: typeof ToolsRoute
  ReportsAdjustedTrialBalanceRoute: typeof ReportsAdjustedTrialBalanceRoute
  ReportsAdjustingJournalRoute: typeof ReportsAdjustingJournalRoute
  ReportsClosingJournalRoute: typeof ReportsClosingJournalRoute
  ReportsGeneralJournalRoute: typeof ReportsGeneralJournalRoute
  ReportsGeneralLedgerPermanentRoute: typeof ReportsGeneralLedgerPermanentRoute
  ReportsGeneralLedgerTemporaryRoute: typeof ReportsGeneralLedgerTemporaryRoute
  ReportsIncomeStatementRoute: typeof ReportsIncomeStatementRoute
  ReportsPostClosingTrialBalanceRoute: typeof ReportsPostClosingTrialBalanceRoute
  ReportsRetainedEarningsRoute: typeof ReportsRetainedEarningsRoute
  ReportsStatementOfCashFlowRoute: typeof ReportsStatementOfCashFlowRoute
  ReportsStatementOfFinancialPositionRoute: typeof ReportsStatementOfFinancialPositionRoute
  ReportsTrialBalanceRoute: typeof ReportsTrialBalanceRoute
  ReportsUnadjustedTrialBalanceRoute: typeof ReportsUnadjustedTrialBalanceRoute
  ReportsWorksheetRoute: typeof ReportsWorksheetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aiassistant': {
      id: '/aiassistant'
      path: '/aiassistant'
      fullPath: '/aiassistant'
      preLoaderRoute: typeof AiassistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chart-of-accounts': {
      id: '/chart-of-accounts'
      path: '/chart-of-accounts'
      fullPath: '/chart-of-accounts'
      preLoaderRoute: typeof ChartOfAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardian': {
      id: '/guardian'
      path: '/guardian'
      fullPath: '/guardian'
      preLoaderRoute: typeof GuardianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal-entry': {
      id: '/journal-entry'
      path: '/journal-entry'
      fullPath: '/journal-entry'
      preLoaderRoute: typeof JournalEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/periods': {
      id: '/periods'
      path: '/periods'
      fullPath: '/periods'
      preLoaderRoute: typeof PeriodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/adjusted-trial-balance': {
      id: '/reports/adjusted-trial-balance'
      path: '/reports/adjusted-trial-balance'
      fullPath: '/reports/adjusted-trial-balance'
      preLoaderRoute: typeof ReportsAdjustedTrialBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/adjusting-journal': {
      id: '/reports/adjusting-journal'
      path: '/reports/adjusting-journal'
      fullPath: '/reports/adjusting-journal'
      preLoaderRoute: typeof ReportsAdjustingJournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/closing-journal': {
      id: '/reports/closing-journal'
      path: '/reports/closing-journal'
      fullPath: '/reports/closing-journal'
      preLoaderRoute: typeof ReportsClosingJournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/general-journal': {
      id: '/reports/general-journal'
      path: '/reports/general-journal'
      fullPath: '/reports/general-journal'
      preLoaderRoute: typeof ReportsGeneralJournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/general-ledger-permanent': {
      id: '/reports/general-ledger-permanent'
      path: '/reports/general-ledger-permanent'
      fullPath: '/reports/general-ledger-permanent'
      preLoaderRoute: typeof ReportsGeneralLedgerPermanentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/general-ledger-temporary': {
      id: '/reports/general-ledger-temporary'
      path: '/reports/general-ledger-temporary'
      fullPath: '/reports/general-ledger-temporary'
      preLoaderRoute: typeof ReportsGeneralLedgerTemporaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/income-statement': {
      id: '/reports/income-statement'
      path: '/reports/income-statement'
      fullPath: '/reports/income-statement'
      preLoaderRoute: typeof ReportsIncomeStatementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/post-closing-trial-balance': {
      id: '/reports/post-closing-trial-balance'
      path: '/reports/post-closing-trial-balance'
      fullPath: '/reports/post-closing-trial-balance'
      preLoaderRoute: typeof ReportsPostClosingTrialBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/retained-earnings': {
      id: '/reports/retained-earnings'
      path: '/reports/retained-earnings'
      fullPath: '/reports/retained-earnings'
      preLoaderRoute: typeof ReportsRetainedEarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/statement-of-cash-flow': {
      id: '/reports/statement-of-cash-flow'
      path: '/reports/statement-of-cash-flow'
      fullPath: '/reports/statement-of-cash-flow'
      preLoaderRoute: typeof ReportsStatementOfCashFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/statement-of-financial-position': {
      id: '/reports/statement-of-financial-position'
      path: '/reports/statement-of-financial-position'
      fullPath: '/reports/statement-of-financial-position'
      preLoaderRoute: typeof ReportsStatementOfFinancialPositionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/trial-balance': {
      id: '/reports/trial-balance'
      path: '/reports/trial-balance'
      fullPath: '/reports/trial-balance'
      preLoaderRoute: typeof ReportsTrialBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/unadjusted-trial-balance': {
      id: '/reports/unadjusted-trial-balance'
      path: '/reports/unadjusted-trial-balance'
      fullPath: '/reports/unadjusted-trial-balance'
      preLoaderRoute: typeof ReportsUnadjustedTrialBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/worksheet': {
      id: '/reports/worksheet'
      path: '/reports/worksheet'
      fullPath: '/reports/worksheet'
      preLoaderRoute: typeof ReportsWorksheetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiassistantRoute: AiassistantRoute,
  AuthRoute: AuthRoute,
  ChartOfAccountsRoute: ChartOfAccountsRoute,
  DashboardRoute: DashboardRoute,
  GuardianRoute: GuardianRoute,
  JournalEntryRoute: JournalEntryRoute,
  PeriodsRoute: PeriodsRoute,
  SettingsRoute: SettingsRoute,
  ToolsRoute: ToolsRoute,
  ReportsAdjustedTrialBalanceRoute: ReportsAdjustedTrialBalanceRoute,
  ReportsAdjustingJournalRoute: ReportsAdjustingJournalRoute,
  ReportsClosingJournalRoute: ReportsClosingJournalRoute,
  ReportsGeneralJournalRoute: ReportsGeneralJournalRoute,
  ReportsGeneralLedgerPermanentRoute: ReportsGeneralLedgerPermanentRoute,
  ReportsGeneralLedgerTemporaryRoute: ReportsGeneralLedgerTemporaryRoute,
  ReportsIncomeStatementRoute: ReportsIncomeStatementRoute,
  ReportsPostClosingTrialBalanceRoute: ReportsPostClosingTrialBalanceRoute,
  ReportsRetainedEarningsRoute: ReportsRetainedEarningsRoute,
  ReportsStatementOfCashFlowRoute: ReportsStatementOfCashFlowRoute,
  ReportsStatementOfFinancialPositionRoute:
    ReportsStatementOfFinancialPositionRoute,
  ReportsTrialBalanceRoute: ReportsTrialBalanceRoute,
  ReportsUnadjustedTrialBalanceRoute: ReportsUnadjustedTrialBalanceRoute,
  ReportsWorksheetRoute: ReportsWorksheetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
